name: native_screenshot_ext
description: A extension of a plugin `https://gitlab.com/ivanjpg/native_screenshot`, to take screenshots using native code (iOS & Android).
version: 1.0.0
email: Dhirendra Singh <dhiruregister@gmail.com>
homepage: https://github.com/gdagitrep/native_screenshot_ext.git
repository: https://github.com/gdagitrep/native_screenshot_ext.git
issue_tracker: https://github.com/gdagitrep/native_screenshot_ext/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dsquare90.native_screenshot_ext
        pluginClass: NativeScreenshotPlugin
      ios:
        pluginClass: NativeScreenshotPlugin
